baseURL = "https://ocamlsyntax.com/"
languageCode = "en-us"
title = "OCaml Syntax"
disableHugoGeneratorInject = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomy", "taxonomyTerm"]
[outputs]
  home = ["HTML"]
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser.attribute]
  block = true
[params]
  author = "Ian Henry"
  email = "ianthehenry@gmail.com"
  description = "OCaml Syntax Cheatsheet"
  tweeter = "@ianthehenry"
